apiVersion: v2
name: paperless-ngx
description: A Helm chart to install paperless-ngx

type: application

version: 0.2.0

appVersion: "2.2.1"

dependencies:
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
