apiVersion: v2
name: paperless-ngx
description: A Helm chart to install paperless-ngx

type: application

version: 0.5.0

appVersion: "2.7.2"

dependencies:
  - name: redis
    version: "19.1.0"
    repository: "https://charts.bitnami.com/bitnami"
