apiVersion: v2
name: paperless-ngx
description: A Helm chart to install paperless-ngx
type: application
version: 0.8.2
appVersion: "2.20.10"
dependencies:
  - name: redis
    version: "25.3.1"
    repository: "https://charts.bitnami.com/bitnami"
