apiVersion: v2
name: paperless-ngx
description: A Helm chart to install paperless-ngx
type: application
version: 0.8.0
appVersion: "2.20.6"
dependencies:
  - name: redis
    version: "24.1.2"
    repository: "https://charts.bitnami.com/bitnami"
