apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-pvc
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 6 }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  {{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName }}
  {{- end }}
